FROM node:14.15-alpine As builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# "RUN npm run start"가 exit할 때가지 Docker Image가 생성되지 않는다.
# 그래서, devcontainer에서 "postStartCommand": "npm start"로 실행해야 한다
# RUN npm run start

# Install global ng-cli if you need
# RUN su node -c "npm install -g @angular/cli npm"

# or if package.json already has ng-cli as dev-tools
# set path to use node_modules/.bin/ng
# ENV PATH="./node_modules/.bin:$PATH"

# RUN ng build --prod # instead of RUN npm run build --prod

# RUN npm run build --prod

# FROM nginx:1.15.8-alpine

# COPY --from=builder /usr/src/app/dist/angular-starter/ /usr/share/nginx/html
